[tools]
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
description = "環境構築用のセットアップコマンド"
run = "uv sync"

[tasks.format]
description = "ソースコードのフォーマット"
run = "ruff format"
