[project]
name = "Clothica_Pattern_Generator"
version = "0.0.1"
description = "auto generate mesh from various cloth patterns."
requires-python = "==3.11.*"

dependencies = [
    "bpy==4.2.0",
]

[dependency-groups]
dev = [
    "fake-bpy-module-4-2>=20250130",
]
